application: rabbit-media1
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /user_guide
  static_dir: codeigniter/user_guide

- url: /assets/js
  static_dir: assets/js

- url: /assets/css
  static_dir: assets/css

- url: /assets/image
  static_dir: assets/image

- url: /
  script: codeigniter/index.php

- url: /(.+)
  script: codeigniter/index.php
